output_dir_folder: /path/to/output/dir/store/predictions
input_dir_folder: /path/to/data

data_name: cropharvest_togo-eval_crop #options are cropharvest_Kenya_maize, cropharvest_global_crop, cropharvest_togo-eval_crop

methods_to_plot: null #consider all

plot_runs: False
