output_dir_folder: /home/mena/Documents/PhD/views_23/views_analysis_IGARSSext/outputs_test
input_dir_folder: /home/mena/Documents/PhD/views_23/data

data_name: cropharvest_togo-eval_crop

training:
  max_epochs: 1000
  batch_size: 256
  emb_dim: 64
  early_stop_args:
    min_delta: 0.01
    mode: min
    patience: 5
    verbose: True
experiment:
  runs: 10
  val_size: 0.1
  mlflow_runs_exp: True
  preprocess:
    fillnan: False
    flatten: False
    form: zscore

view_names: ["S2","S1","weather", "VI"]

architecture:
  encoders:
    model_type: gru
    n_layers: 2
    layer_size: 64
    dropout: 0.2
    batchnorm: False

    # model_type: tae
    # dropout: 0.2
    # #default values:
    # layer_sizes: [512, 128] #256-128 in LTAE and 512-128-128 in TAE
    # d_k: 8 #8 in LTAE and 32 in TAE
    # n_head: 4 #16 in LTAE and 4 in TAE
    # d_model: 128 #256 in LTAE and None in TAE, test with 128

    # model_type: tempcnn
    # dropout: 0.2
    # kernel_size: 5 #default value: 5
    # layer_size: 64 #default value: 64
    # n_layers: 3 #default value: 3
  predictive_model:
    n_layers: 1
    layer_size: 64
    dropout: 0.2
    batchnorm: True
